=== sad-pandita/practica_1/estructura_datos.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT videoteca (nombre, ubicacion, pelicula+, fecha_ultima_act) >

<!ELEMENT nombre (#PCDATA) >
<!ELEMENT ubicacion (#PCDATA) >
<!ELEMENT fecha_ultima_act (#PCDATA) >



<!ELEMENT pelicula (titulo, duracion, año, sinopsis, reparto, genero, enlace) >

<!ELEMENT titulo (#PCDATA) >
<!ELEMENT duracion (#PCDATA) >
<!ELEMENT año (#PCDATA) >
<!ELEMENT sinopsis (#PCDATA) >
<!ELEMENT genero (#PCDATA) >
<!ELEMENT enlace (#PCDATA) >



<!ELEMENT reparto (actores+) >



<!ELEMENT actores (nombre_a, enlace_wiki) >

<!ELEMENT nombre_a (#PCDATA) >
<!ELEMENT enlace_wiki (#PCDATA) >

=== sad-pandita/practica_1/videoteca.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE videoteca SYSTEM "estructura_datos.dtd">

<videoteca>
	<nombre></nombre>
	<ubicacion></ubicacion>
	<fecha_ultima_act></fecha_ultima_act>

	<pelicula>
		<titulo></titulo>
		<duracion></duracion>
		<año></año>
		<sinopsis></sinopsis>
		<genero></genero>
		<enlace></enlace>
		
		<reparto>
			<actores>
				<nombre_a></nombre_a>
				<enlace_wiki></enlace_wiki>
			</actores>
		</reparto>


	</pelicula>


</videoteca>
